declare var __REACT_DEVTOOLS_TARGET_WINDOW__: any;
declare var __REACT_DEVTOOLS_GLOBAL_HOOK__: any;
declare var __componentInspector__: any;
declare var __defineGetter__: any;
declare var __defineSetter__: any;
declare var __HAPPY_INSPECTOR__: any;
declare module '*.scss';
declare var React: any;
declare var ReactDom: any;
declare var chrome: any;
